# Generated by Django 5.1.4 on 2024-12-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.TextField()),
                ('convo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.conversation')),
            ],
        ),
    ]
